# kubectl create secret generic app-secret --from-literal=port=3000 --from-file=Dockerfile=./Dockerfile
apiVersion: v1
data:
  Dockerfile: RlJPTSBub2RlOjE0LWFscGluZQoKV09SS0RJUiAvdXNyL3NyYy9hcHAKCkNPUFkgcGFja2FnZSouanNvbiAuLwoKUlVOIG5wbSBpbnN0YWxsCgpDT1BZIC4gLgoKQ01EIFsgIm5wbSIsICJzdGFydCIgXQ==
  port: MzAwMA==
kind: Secret
metadata:
  name: app-secret
  namespace: default
type: Opaque